import type { Metadata } from 'next';
import localFont from 'next/font/local';
// @ts-ignore
import cls from './globals.css';
import { ClientSdkProvider } from '@/lib/clientsdkprovider';
import Script from "next/script";

const ManropeLight = localFont({
    src: './../../public/fonts/Manrope/Manrope-Light.woff2',
    variable: '--font-manrope-300',
    weight: '300',
});

const ManropeRegular = localFont({
    src: './../../public/fonts/Manrope/Manrope-Regular.woff2',
    variable: '--font-manrope-400',
    weight: '400',
});

const ManropeMedium = localFont({
    src: './../../public/fonts/Manrope/Manrope-Medium.woff2',
    variable: '--font-manrope-500',
    weight: '500',
});

const ManropeSemiBold = localFont({
    src: './../../public/fonts/Manrope/Manrope-SemiBold.woff2',
    variable: '--font-manrope-600',
    weight: '600',
});

const ManropeBold = localFont({
    src: './../../public/fonts/Manrope/Manrope-Bold.woff2',
    variable: '--font-manrope-700',
    weight: '700',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    console.log('root');
    return (
        <html lang="en">
        <body className={`
            ${ManropeLight.variable} 
            ${ManropeRegular.variable} 
            ${ManropeMedium.variable} 
            ${ManropeSemiBold.variable} 
            ${ManropeBold.variable} 
            ${cls}
            antialiased`}>
        <script
            src="https://drag-drop-touch-js.github.io/dragdroptouch/dist/drag-drop-touch.esm.min.js"
            type="module"
        ></script>
        <ClientSdkProvider>{children}</ClientSdkProvider>
        </body>
        </html>
    );
}
