version: "3.8"

services:
  app:
    container_name: bokko-twa
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "https://bokko.grabitkorovany.org/"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://bokko.grabitkorovany.org/
    networks:
      - bokko_web_network

networks:
  bokko_web_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1
