services:
  app:
    container_name: bokko-twa
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "https://bokko.grabitkorovany.org/"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=https://bokko.grabitkorovany.org/
    networks:
      bokko_web_network:
        ipv4_address: 172.27.0.2
